# Site settings
tagline: Cabra Flashcards

description: A free, open-source, cross-platform studying app with over 230,000 users worldwide.
url: http://cabra.hathix.com
angular_version: 1.3.8
bootstrap_version: 3.3.1
jquery_version: 1.11.2
fontawesome_version: 4.2.0

# Build settings
markdown: kramdown
permalink: pretty
